### ISSUE TITLE
Upcoming hackathon

### ISSUE THREAD

**Issue by elie222** [500tech/kapow-extension#1]
Saw you guys pitch this at the event a few months back. An upcoming blockchain hackathon happening in 2 weeks from now if you're interested:

https://dappworks.co/dappathon

**Comment by adamkleingit** [comment]
@elie222 Can you share your contact details? There are many things unclear from the website. Thanks

**Comment by elie222** [comment]
Yes, hello@dappworks.co. What information would you like to know?
